# Pipeline to do the following:
# - Create a new VM from a marketplace image

trigger: none

pool: my-hosted-pool

variables:
  # added as variables in the pipeline editor
  #armConnection: ''
  #subscriptionId: ''
  rgName: ''
  location: ''

steps:
# create a starter VM using an existing ARM template
# this template assumes that a vNEt and a subnet already exist.
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(armConnection)
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(rgName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.Repository.LocalPath)\template.json'
    csmParametersFile: '$(Build.Repository.LocalPath)\parameters.json'
    deploymentMode: 'Incremental'