# Pipeline to do the following:
# - Create a new VM from a marketplace image
#
# Author : Mitush Yadav
# https://github.com/MitushYadav

trigger: none

pool:
  # or use a self hosted pool
  vmImage: 'windows-latest'

variables:
  # add the following 2 variables as pipeline editor variables, for security
  #armConnection: ''
  #subscriptionId: ''
  # specify the resource group to deploy the VM and its resources to
  rgName: ''
  # specify the location of the resources, generally the location of the resource group
  location: ''

steps:
# create a VM using an ARM template. The associated ARM template is present under templates\arm\basevm
# this template assumes that a vNEt and a subnet already exist. Edit the required information in the parameters file.
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(armConnection)
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(rgName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.Repository.LocalPath)\template.json'
    csmParametersFile: '$(Build.Repository.LocalPath)\parameters.json'
    deploymentMode: 'Incremental'