# Pipeline to do the following:
# - Create new VMs from the ACG image and install the required software to allow them to act as session hosts for the given hostpool.
#
# Author : Mitush Yadav
# https://github.com/MitushYadav

trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  # add the following 2 variables as pipeline editor variables, for security
  #armConnection: ''
  #subscriptionId: ''
  # specify the resource group name to deploy the resources to
  rgName: ''
  # specify the location for the resources, generally the resource group location
  location: ''
  # specify the prefix for the session host VMs
  sessionHostNamePrefix: ''
  # specify the number of session hosts to deploy, as number
  numberOfSessionHosts: 

steps:
# deploy the ARM template for creating AVD session hosts. The template is present under templates\arm\sessionhosts
# this template assumes that a vNEt and a subnet already exist. Specify the required information in the parameters file
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: $(armConnection)
    subscriptionId: $(subscriptionId)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(rgName)
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.Repository.LocalPath)\template.json'
    csmParametersFile: '$(Build.Repository.LocalPath)\parameters.json'
    overrideParameters: '-rdshPrefix $(sessionHostNamePrefix) -rdshNumberOfInstances $(numberOfSessionHosts)'
    deploymentMode: 'Incremental'